version: '3'

tasks:
  run-agent:
    cmds:
      - pip install '../colang/dist/agentman-0.1-py3-none-any.whl' --force-reinstall
      - python -m agentman.run.agent agent
  
  run-tools:
    cmds:
      - pip install '../colang/dist/agentman-0.1-py3-none-any.whl' --force-reinstall
      - python -m agentman.run.tools Gmail