version: '3'

dotenv:
  - .env

tasks:
  run-agent:
    cmds:
      - pip install '../colang/dist/agentman-0.0.2-py3-none-any.whl' --force-reinstall
      - python -m agentman.run.agent agent
  
  run-tools:
    cmds:
      - pip install '../colang/dist/agentman-0.0.2-py3-none-any.whl' --force-reinstall
      - python -m agentman.run.tool